#!/usr/bin/env python3

'''
Check if dependencies are correctly located and installed
 1) GeneMark
 2) RepeatModeler
 3) Hisat2
 4) Trinity
 5) Maker
 6) Braker
 7) BUSCO
 8) Pfam Scan
 9) Blast
 10) Samtools

Output: the locations will be written in 'fungap_config.json' file
Last updated: May 1, 2025
'''

import sys
from argparse import ArgumentParser
from pathlib import Path
import json

TOOLS = [
    'gmes_petap.pl', 'gmhmme3', 'probuild', 'BuildDatabase', 'RepeatModeler',
    'hisat2', 'Trinity', 'maker', 'gff3_merge', 'fasta_merge', 'maker2zff',
    'fathom', 'forge', 'hmm-assembler.pl', 'braker.pl', 'busco', 'pfam_scan.pl',
    'blastp', 'blastn', 'blastx', 'makeblastdb', 'samtools', 'bamtools',
    'augustus']
MICROMAMBA_RUNS = {
    'BuildDatabase': 'micromamba run --name repeatmodeler BuildDatabase',
    'RepeatModeler': 'micromamba run --name repeatmodeler RepeatModeler',
    'hisat2': 'micromamba run --name hisat2 hisat2',
    'Trinity': 'micromamba run --name trinity Trinity',
    'maker': 'micromamba run --name maker maker',
    'gff3_merge': 'micromamba run --name maker gff3_merge',
    'fasta_merge': 'micromamba run --name maker fasta_merge',
    'maker2zff': 'micromamba run --name maker maker2zff',
    'fathom': 'micromamba run --name maker fathom',
    'forge': 'micromamba run --name maker forge',
    'hmm_assembler.pl': 'micromamba run --name maker hmm-assembler.pl',
    'breaker.pl': 'micromamba run --name braker3 braker.pl',
    'busco': 'micromamba run --name busco busco',
    'pfam_scan.pl': 'micromamba run --name pfam_scan pfam_scan.pl',
    'blastp': 'micromamba run --name maker blastp',
    'blastn': 'micromamba run --name maker blastn',
    'blastx': 'micromamba run --name maker blastx',
    'makeblastdb': 'micromamba run --name maker makeblastdb',
    'samtools': 'micromamba run --name maker samtools',
    'bamtools': 'micromamba run --name maker bamtools',
    'augustus': 'micromamba run --name maker augustus'}


def main():
    '''Main function'''
    argparse_usage = (
        'check_dependencies.py -p <pfam_db_path> -g <genemark_path> '
        '-m <maker_path>')
    parser = ArgumentParser(usage=argparse_usage)
    parser.add_argument(
        '-p', '--pfam_db_path', type=Path, required=True,
        help='Pfam database path')
    parser.add_argument(
        '-g', '--genemark_path', type=Path, required=True,
        help='GeneMark bin path')
    parser.add_argument(
        '-o', '--output_json', type=Path, default='fungap_config.json',
        help='Output FunGAP config JSON file (default: fungap_config.json)')

    args = parser.parse_args()
    pfam_db_path = args.pfam_db_path.resolve()
    genemark_path = args.genemark_path.resolve()
    output_json = args.output_json.resolve()

    # Get the path of dependencies
    d_run = build_run(genemark_path)
    check_binary(d_run)
    check_db(pfam_db_path)
    write_config(d_run, pfam_db_path, output_json)


def build_run(genemark_path):
    '''Build run: genemark from input, and micromamba runs'''
    d_run = {}
    d_run['gmes_petap.pl'] = f'micromamba run --name braker3 {genemark_path / "gmes_petap.pl"}'
    d_run['gmhmme3'] = f'micromamba run --name braker3 {genemark_path / "gmhmme3"}'
    d_run['probuild'] = f'micromamba run --name braker3 {genemark_path / "probuild"}'
    d_run |= MICROMAMBA_RUNS
    return d_run


def check_db(pfam_db_path):
    '''Check pfam_db_path'''
    if not pfam_db_path.is_dir():
        sys.exit(f'[ERROR] Pfam directory does not exist: {pfam_db_path}')
    file_names = {item.name for item in pfam_db_path.iterdir()}
    pfam_files = {
        'Pfam-A.hmm.h3f', 'Pfam-A.hmm.h3i', 'Pfam-A.hmm.h3m', 'Pfam-A.hmm.h3p',
        'Pfam-A.hmm', 'Pfam-A.hmm.dat'}
    if not pfam_files.issubset(file_names):
        sys.exit(
            '[ERROR] Pfam files are not found. Six files (Pfam-A.hmm  '
            'Pfam-A.hmm.dat Pfam-A.hmm.h3f Pfam-A.hmm.h3i Pfam-A.hmm.h3m '
            f'Pfam-A.hmm.h3p) should be located at {pfam_db_path} directory.'
            'These files can be generated by "hmmpress Pfam-A.hmm" command')
    return pfam_db_path


def check_binary(d_run):
    '''Check if the tool works properly'''
    print('Please run the following command to check if the tool works properly:')
    print('If the command fails, check your installation or adjust fungap_config.json')
    for tool_name, tool_run in d_run.items():
        if tool_name in ['gmes_petap.pl', 'gmhmme3', 'probuild']:
            print(f'{tool_run}')
        elif tool_name in ['pfam_scan.pl']:
            print(f'{tool_run} --h')
        else:
            print(f'{tool_run} --help')


def write_config(d_run, pfam_db_path, output_json):
    '''Write config file as JSON'''
    print('Writing config file as JSON')
    d_config = d_run | {'pfam_db_path': str(pfam_db_path)}
    with output_json.open('w') as f_out:
        json.dump(d_config, f_out, indent=4)


if __name__ == '__main__':
    main()
